const fs = require('fs');
const path = require('path');
const { readCatalog } = require('./lib/read-catalog');
const { renderCollectionPage } = require('./lib/render-collection');
const { renderProductPage } = require('./lib/render-product');
const { renderSitemap, renderRobots } = require('./lib/render-sitemap');
const { renderSearchIndex } = require('./lib/render-search-index');
const { renderSearchPage } = require('./lib/render-search-page');

// Load size group metadata from the migration model so the renderer can
// emit a 2D size×finish picker on merged product pages.
function loadSizeDataMap() {
  const modelPath = path.join(path.join(__dirname, '..'), 'catalog.model.json');
  if (!fs.existsSync(modelPath)) return new Map();
  const model = JSON.parse(fs.readFileSync(modelPath, 'utf8'));
  const map = new Map();
  for (const g of model.groups) {
    if (g.isSizeGroup) map.set(`${g.collectionSlug}::${g.groupSlug}`, g);
  }
  return map;
}

const SITE_BASE_URL = 'https://ipmbathfittings.com';

const ROOT = path.join(__dirname, '..');
// Generated by the migration pipeline (npm run migrate) from "ITEM MASTER FOR WEBSITE.xls".
const CATALOG_FILE = path.join(ROOT, 'catalog.generated.xlsx');

function writeFile(outPath, content) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, 'utf8');
}

function main() {
  const sizeDataMap = loadSizeDataMap();
  const result = readCatalog(CATALOG_FILE);
  const { collections, productGroups, warnings, errors, missingImages } = result;

  if (errors.length) {
    console.error('Build failed with errors:');
    errors.forEach(e => console.error(`  ERROR: ${e}`));
    process.exit(1);
  }

  if (warnings.length) {
    console.log('Warnings:');
    warnings.forEach(w => console.log(`  WARN: ${w}`));
  }

  let collectionPages = 0;
  let productPages = 0;

  for (const collection of collections) {
    const groupsInCollection = productGroups.filter(g => g.collectionSlug === collection.slug);
    if (groupsInCollection.length === 0) continue; // skip empty collections for this phase

    const html = renderCollectionPage(collection, productGroups, collections, { siteBaseUrl: SITE_BASE_URL });
    const outPath = path.join(ROOT, 'collections', collection.slug, 'index.html');
    writeFile(outPath, html);
    collectionPages++;

    for (const group of groupsInCollection) {
      const sizeData = sizeDataMap.get(`${group.collectionSlug}::${group.groupSlug}`) || null;
      const productHtml = renderProductPage(group, collection, { siteBaseUrl: SITE_BASE_URL, sizeData });
      const productOutPath = path.join(ROOT, 'collections', group.collectionSlug, group.groupSlug, 'index.html');
      writeFile(productOutPath, productHtml);
      productPages++;
    }
  }

  // Sitemap + robots.txt (only for collections/products actually generated)
  const generatedCollections = collections.filter(c => productGroups.some(g => g.collectionSlug === c.slug));
  const sitemap = renderSitemap(generatedCollections, productGroups, SITE_BASE_URL);
  writeFile(path.join(ROOT, 'sitemap.xml'), sitemap);

  const robotsPath = path.join(ROOT, 'robots.txt');
  if (!fs.existsSync(robotsPath)) {
    writeFile(robotsPath, renderRobots(SITE_BASE_URL));
  }

  // Client-side search index (name / SKU / collection / category)
  writeFile(path.join(ROOT, 'search-index.json'), renderSearchIndex(generatedCollections, productGroups));

  // Search page (generated so it shares the full design system)
  writeFile(path.join(ROOT, 'search.html'), renderSearchPage(generatedCollections, { siteBaseUrl: SITE_BASE_URL }));

  if (missingImages.length) {
    console.log('\nMissing images (using fallbacks):');
    missingImages.forEach(m => console.log(`  ${m}`));
  }

  console.log(`\nGenerated ${collectionPages} collection page(s), ${productPages} product page(s). ${missingImages.length} missing image(s) (see above).`);
}

main();
